import '../utils/icons.dart';
import 'my_page_info.dart';

class FakeData {
  static List<MyPageInfo> getMyPages() {
    List<MyPageInfo> myPagesInfo = [];
    myPagesInfo.add(MyPageInfo(phoneName: "Redmi Note 11 Pro", imgUrl: MyIcons.redmi11, colorName: 'Atlantic Blue', price: '275',
      wikiText: '''The Redmi Note 11 is a line of Android-based smartphones as part of the Redmi Note series by Redmi, a sub-brand of Xiaomi Inc. Global lineup comprises the Redmi Note 11, Note 11S, Note 11S 5G, Note 11 Pro, Note 11 Pro 5G, Note 11 Pro+. Chinese lineup consists of the Redmi Note 11 4G, Note 11 5G, Note 11 Pro, Note 11E, Note 11E Pro. Indian lineup comprises the Redmi Note 11, Note 11S and Note 11T. In India Chinese variant of Redmi Note 11 Pro and Note 11 Pro+ are sold as Xiaomi 11i (not to be confused with Mi 11i) and Xiaomi 11i HyperCharge in accordance.[11][12] In November 2021, Poco M4 Pro 5G was announced. It was based on redmi Note 11 5G but with MicroSD card slot, different design and more storage configuration. In March 2022, was announced Redmi Note 11S 5G which has same design as Redmi Note 11 5G but also has MicroSD card slot, different camera setup and more storage configuration. On global market Redmi Note 11E was annonced in March 2022 as Redmi 10 5G. The Redmi Note 11 is a line of Android-based smartphones as part of the Redmi Note series by Redmi, a sub-brand of Xiaomi Inc. Global lineup comprises the Redmi Note 11, Note 11S, Note 11S 5G, Note 11 Pro, Note 11 Pro 5G, Note 11 Pro+. Chinese lineup consists of the Redmi Note 11 4G, Note 11 5G, Note 11 Pro, Note 11E, Note 11E Pro. Indian lineup comprises the Redmi Note 11, Note 11S and Note 11T. In India Chinese variant of Redmi Note 11 Pro'''),);
    myPagesInfo.add(MyPageInfo(phoneName: "Redmi Note 10 Pro", imgUrl: MyIcons.pro10, colorName: 'Moccasin', price: '240', wikiText: "The Redmi Note 10 is a line of Android-based smartphones as part of the Redmi Note series by Redmi, a sub-brand of Xiaomi Inc. Global lineup comprises the Redmi Note 10, Note 10S, Note 10S 4G, Note 10 Pro, Note 10 Pro 5G, Note 10 Pro+. Chinese lineup consists of the Redmi Note 10 4G, Note 10 5G, Note 10 Pro, Note 10E, Note 11E Pro. Indian lineup comprises the Redmi Note 10, Note 10S and Note 10T. In India Chinese variant of Redmi Note 10 Pro and Note 10 Pro+ are sold as Xiaomi 10i (not to be confused with Mi 10i) and Xiaomi 10i HyperCharge in accordance. In November 2021, Poco M4 Pro 5G was announced. It was based on redmi Note 10 5G but with MicroSD card slot, different design and more storage configuration. In March 2022, was announced Redmi Note 10S 5G which has same design as Redmi Note 10 5G but also has MicroSD card slot, different camera setup and more storage configuration. On global market Redmi Note 11E was annonced in March 2022 as Redmi 10 5G. The Redmi Note 11 is a line of Android-based smartphones as part of the Redmi Note series by Redmi, a sub-brand of Xiaomi Inc. Global lineup comprises the Redmi Note 11, Note 11S, Note 11S 5G, Note 11 Pro, Note 11 Pro 5G, Note 11 Pro+. Chinese lineup consists of the Redmi Note 11 4G, Note 11 5G, Note 11 Pro, Note 11E, Note 11E Pro. Indian lineup comprises the Redmi Note 11, Note 11S and Note 11T. In India Chinese variant of Redmi Note 11 ProThe Redmi Note 11 is a line of Android-based smartphones as part of the Redmi Note series by Redmi, a sub-brand of Xiaomi Inc. Global lineup comprises the Redmi Note 11, Note 11S, Note 11S 5G, Note 11 Pro, Note 11 Pro 5G, Note 11 Pro+. Chinese lineup consists of the Redmi Note 11 4G, Note 11 5G, Note 11 Pro, Note 11E, Note 11E Pro. Indian lineup comprises the Redmi Note 11, Note 11S and Note 11T. In India Chinese variant of Redmi Note 11 Pro and Note 11 Pro+ are sold as Xiaomi 11i (not to be confused with Mi 11i) and Xiaomi 11i HyperCharge in accordance.[11][12] In November 2021, Poco M4 Pro 5G was announced. It was based on redmi Note 11 5G but with MicroSD card slot, different design and more storage configuration. In March 2022, was announced Redmi Note 11S 5G which has same design as Redmi Note 11 5G but also has MicroSD card slot, different camera setup and more storage configuration. On global market Redmi Note 11E was annonced in March 2022 as Redmi 10 5G. The Redmi Note 10 is a line of Android-based smartphones as part of the Redmi Note series Pro, Note, Note 10 Pro+. Chinese lineup consists of the Redmi Note , Note 10S and Note 10T. In India Chinese variant of Redmi Note 10 Pro",),);
    myPagesInfo.add(MyPageInfo(phoneName: "Redmi Note 9 Pro", imgUrl: MyIcons.pro9, colorName: 'Tropical Green', price: '225', wikiText: '''
The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 9 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 9 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 9 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. 
    ''',),);
    myPagesInfo.add(MyPageInfo(phoneName: "Redmi Note 8 Pro", imgUrl: MyIcons.pro8, colorName: 'Matte Black', price: '200', wikiText: '''
The Redmi Note 8 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 8 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 8 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 8 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. 
    ''',),);
    myPagesInfo.add(MyPageInfo(phoneName: "Redmi Note 7 Pro", imgUrl: MyIcons.pro7, colorName: 'Ocean Black', price: '195', wikiText: '''
The Redmi Note 7 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 7 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 7 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 7 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. 
    ''',),);
    myPagesInfo.add(MyPageInfo(phoneName: "Redmi Note 6 Pro", imgUrl: MyIcons.pro6, colorName: 'Rose Gold', price: '180', wikiText: '''
The Redmi Note 6 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 6 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 6 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 6 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. ''',),);
    myPagesInfo.add(MyPageInfo(phoneName: "Redmi Note 5 Pro", imgUrl: MyIcons.redmi5, colorName: 'Great Black', price: '120', wikiText: '''
The Redmi Note 5 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 5 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 5 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. The Redmi Note 9 Pro has a lower starting price than its predecessors, but also doesn't offer all the modern features that you might expect. It has a 6.67-inch LCD screen with a 60Hz refresh rate and hole-punch front camera at the top. The processor is a Qualcomm Snapdragon 720G which is surprisingly powerful for this segment. You also get a 5020mAh battery and suppport for 18W fast charging. 
The Redmi Note 5 Pro is powerful and everyday work will go smoothly. The display is large and crisp, making games and movies look good. You have a choice between variants, one with 4GB of RAM and 64GB of storage, and the other with 6GB of RAM and 128GB of storage.
The 48-megapixel primary camera was slightly disappointing overall, particularly in low light. There's also an 8-megapixel wide-angle camera, a 5-megapixel macro camera, and a 2-megapixel depth sensor. On the front you get a 16-megapixel selfie camera. 
    ''',),);
    return myPagesInfo;
  }
}
